language: python
env:
  - TOX_ENV=py26-1.4
  - TOX_ENV=py26-1.5
  - TOX_ENV=py26-1.6
  - TOX_ENV=py27-1.4
  - TOX_ENV=py27-1.5
  - TOX_ENV=py27-1.6
  - TOX_ENV=py27-trunk
  - TOX_ENV=py33-1.5
  - TOX_ENV=py33-1.6
  - TOX_ENV=py33-trunk
  - TOX_ENV=pypy-1.4
  - TOX_ENV=pypy-1.5
  - TOX_ENV=pypy-1.6
  - TOX_ENV=pypy-trunk
before_install:
  - export DJANGO_SETTINGS_MODULE=autofixture_tests.settings
  - sudo pip install tox
script:
  - tox -e $TOX_ENV -v
branches:
  only:
    - master

